%% MATLAB Assignment 1 [Output]
%% Exercise 1

disp("===== Exercise 1 =====");
[~, ~, ...
  A, b, c, D, x1, x2, x3, aug, ...
  x4, x5, x6, x7, x8, ...
  F1, F2, E, m, n, E1, E2] = Exercise1()
disp("=========================");
%% Exercise 2

disp("===== Exercise 2 =====");
[~, ~, B, pivcols, compare, m, n, solution_type] = Exercise2(A, b)
disp("=========================");
%% Exercise 3

disp("===== Exercise 3 =====");
[~, ~, ...
  bA, A1, Ab1, sol1, A2, Ab2, sol2, A3, Ab3, sol3, ...
  example_A1, example_b1, example_type1, ...
  bC, A4, Ab4, sol4, A5, Ab5, sol5, A6, Ab6, sol6, ...
  example_A2, example_b2, example_type2, ...
  example_A3, example_b3, example_type3] = Exercise3()
disp("=========================");
%%